spring:
  profiles:
    active:
      - dog
      - ES
      - dev
guru:
  username: yml-user
  password: yml-password
  jdbcurl: yml-jdbcurl

---
spring:
  profiles: prod
guru:
  username: ymlprod-user
  password: ymlprod-password
  jdbcurl: ymlprod-jdbcurl